### ISSUE TITLE
battery

### ISSUE THREAD

**Issue by ghost** [a-schaefers/posix-shell-power-daemon#2]
Nice script, just what i was looking for so thanks first up.

I modified the script not the config file to point to `/sys/class/power_supply/BAT1`

Just thought maybe some sort of tweak might be in order to have the user choose the correct battery in the config file and not the script perhaps?

**Comment by a-schaefers** [comment]
Hello, I anticipated some people running into this, so it currently fails with the message `printf -- "%s\n" "(SPM) Battery not detected."` if BAT0 does not exist. I only have a system which uses BAT0, so I am unsure how to address this issue currently, until I receive more information.

@clusterF does your computer use two batteries? E.g. BAT0 and BAT1, or does the number simply start with BAT1 for some reason? If it uses two batteries, do you know if there is a reliable method to determine which battery is the primary? Thank you.

**Comment by a-schaefers** [comment]
Okay this is fixed with 496720b

Basically now you can easily change the battery location in config

**Comment by ghost** [comment]
Hi again, i see you found a fix, thanks. My laptop only has one battery but for whatever reason its named BAT1.

Cheers.
